name: GIT
# on:
#   push:
#     branches: [ feature-*,master ]
#   pull_request:
#     branches: [ feature-*,master ]
on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Keys and known_hosts
      env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Some task that fetches dependencies
      env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
            git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
            git remote add dest git@github.com:lttga/dest.git
            git pull --all
            git fetch dest
            git fetch origin
            git remote -v
            git branch -a
            for branch in `git branch -r | grep -w ' origin/feature*' | sed 's/^[^\/]*\///g'` 
            do
              git checkout --track origin/$branch
              git push -f -u dest $branch
            done
            git remote rm dest
            git remote --verbose
